### ISSUE TITLE
Feature request - Battery level

### ISSUE THREAD

**Issue by HDJedi** [neilzilla/hass-renpho#29]
Sorry if this is the wrong place for a request but I was wondering if it was possible to see the battery levels of the scale within Home Assistant?
Great work so far, thank you.

**Comment by neilzilla** [comment]
I don't believe this is possible with the code we have at present.

To see the battery level, you would have to connect to the device directly.  The way we grab the data is over the internet via Renpho's servers, which I don't believe store any information on battery levels.

Also, connecting to the device directly would provide a long list of devices to support, I do not believe this is a realistic goal unfortunately.

**Comment by HDJedi** [comment]
No problem, thought it was worth an ask. Cheers.
