### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Trevsweb** [neilzilla/hass-renpho#3]
Platform error sensor.renpho - Requirements for renpho not found: ['pycryptodome==3.3.1'].
Integration error: renpho - Requirements for renpho not found: ['pycryptodome==3.3.1'].

getting this error when installing
any idea how to install the missing requirement?
running on homeassistant latest ver on x86

**Comment by neilzilla** [comment]
frustratingly when I've added the component to my actual set up I've received no errors so haven't been able to troubleshoot.

What version is the latest you're running, and how are you running it (hardware? docker?)
You can install the dependency manually using pip or pip3 depending on how your home assistant is running.

**Comment by Trevsweb** [comment]
I'm running ha os (latest) on x86 direct on the pc hardware. No docker. 
Can't seem to run pip or pip3 on the terminal. 
I've found a few people mention that they can't install via pip so not sure if it's fixable without the dependency.

**Comment by neilzilla** [comment]
According to this https://github.com/home-assistant/operating-system HAOS runs HA in a docker container still, to check if this is the case (assuming you're not familiar with docker, apologies if so) you could run:

`docker ps`

to list docker containers, find the id of the HA container and then type:
`docker exec -it <id of container> bash`

to get a command prompt inside the container, from there you could install via pip.

Another solution might be to change the dependency version and have a test, I'm not sure how successful this would be as I've not tried it.

If this is no good, I'll set up a dev environment for testing myself.

**Comment by domramsey** [comment]
I'm getting the same error attempting to install. HA, 2022.7 running in a Docker container.

**Comment by neilzilla** [comment]
I've changed the dependency version for pycryptodome, please try redownloading and installing repo

**Comment by Trevsweb** [comment]
cool I updated the files, restarted then loaded the config.yaml sensor stuff and it passed the config check which is great. 
just need to find out my renpho password lol

I've got the Renpho weight sensor now :)

thanks for the update.

**Comment by domramsey** [comment]
Ok, this is no longer producing an error,  but I'm not getting any data or even any entities set up. Can't see anything at all in the log file about renpho.

**Comment by domramsey** [comment]
Ah, I think error in the installation instructions that say the folder should be hass_renpho, but hass-renpho works for me

**Comment by domramsey** [comment]
So I'm now it's starting up but I'm getting the errors: "Error getting scale users: list index out of range" and "Error authenticating: 'RenphoWeight' object has no attribute 'user_id'"

**Comment by neilzilla** [comment]
@domramsey it sounds like it's struggling to get a user to get measurements, do you have any users set up?

**Comment by domramsey** [comment]
I just have the one default user. I've tried adding another user and that doesn't seem to have changed anything. Using your latest updates.

**Comment by Trevsweb** [comment]
2022-08-05 09:34:43.442 ERROR (SyncWorker_5) [custom_components.hass_renpho.RenphoWeight] Error getting scale users: list index out of range
2022-08-05 09:34:43.443 ERROR (SyncWorker_5) [custom_components.hass_renpho.RenphoWeight] Error authenticating: 'RenphoWeight' object has no attribute 'user_id'

this is my current error.
cannot get any data from the scale.
added details to my configuration.yml for the login details but nothing

**Comment by neilzilla** [comment]
it sounds like it's struggling to get a list of users for the scale, I must have coded it purely based on my own setup.
I'm planning on rewriting a lot of the code when I get some time and we can start ironing out these issues.

**Comment by zzz123adfadsf** [comment]
followed your setup guide and got the following. Not sure what to do to fix it.

Logger: custom_components.hass_renpho.RenphoWeight
Source: custom_components/hass_renpho/RenphoWeight.py:18
Integration: hass_renpho
First occurred: 4:21:41 PM (3 occurrences)
Last logged: 4:21:41 PM

Error authenticating: encoding without a string argument
Error getting scale users: 'RenphoWeight' object has no attribute 'session_key'
Error getting measurements: 'RenphoWeight' object has no attribute 'user_id'

**Comment by neilzilla** [comment]
a lot of this has been written since these issues, please check other issues and log a new issue if issue persists.
