### ISSUE TITLE
Error getting measurements: 'RenphoWeight' object has no attribute 'user_id'

### ISSUE THREAD

**Issue by warlordattack** [neilzilla/hass-renpho#4]
Hello i just installed, and get this error after HA restart : 

This error originated from a custom integration.
Logger: custom_components.hass_renpho.RenphoWeight
Source: custom_components/hass_renpho/RenphoWeight.py:81
Integration: hass_renpho
First occurred: 21:11:20 (1 occurrences)
Last logged: 21:11:20
Error getting measurements: 'RenphoWeight' object has no attribute 'user_id'

**Comment by warlordattack** [comment]
This error originated from a custom integration.

Logger: custom_components.hass_renpho.RenphoWeight
Source: custom_components/hass_renpho/RenphoWeight.py:62
Integration: hass_renpho
First occurred: 00:53:08 (2 occurrences)
Last logged: 01:03:09

Error getting scale users: list index out of range

**Comment by warlordattack** [comment]
This error originated from a custom integration.

Logger: custom_components.hass_renpho.RenphoWeight
Source: custom_components/hass_renpho/RenphoWeight.py:56
Integration: hass_renpho
First occurred: 00:53:08 (2 occurrences)
Last logged: 01:03:09

No users set up on scale

**Comment by sergiobonfiglio** [comment]
I had the same issue, but fixed it using a fallback id: "0". Something like this:
```
        except Exception as e:
            _LOGGER.error("Error getting scale users: " + str(e))
            _LOGGER.error("fallback to user_id 0")
            self.user_id = "0"`
```

**Comment by neilzilla** [comment]
if configuration,yaml is set up correct, this looks like the same issue as #3

**Comment by warlordattack** [comment]
finally got renpho weight via fitbit :)
